name: Pull-Request-Dependencies

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
    paths:
      - "package.json"
    tags-ignore:
      - "**"
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
 
permissions:
  contents: read
jobs:
  dependency-report:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
      - name: "get refs"
        id: vars
        run: |
          echo ::set-output name=base_ref::${{ github.event.pull_request.base.ref || github.ref }}
          echo ::set-output name=head_ref::${{ github.event.pull_request.head.ref || github.ref }}
    
      - name: Dependency Review
        uses: actions/dependency-review-action@main
        id: dependency-review
        with:
          fail-on-severity: low
          deny-licenses: LGPL-2.0, BSD-2-Clause, LGPL-3.0, MPL-2.0, AGPL-3.0, Unlicense, Apache-2.0, GPL-3.0, MIT, BSD-3-Clause, BSL-1.0, CC0-1.0, EPL-2.0, GPL-2.0, LGPL-2.1
          base-ref: ${{steps.vars.outputs.base_ref}}
          head-ref: HEAD
      